### ISSUE TITLE
Latest Conda requires "conda activate" instead of "source activate", breaking mlflow run

### ISSUE THREAD

**Issue by ankitmathur-db** [mlflow/mlflow#1507]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OS 10.14.5
- **MLflow installed from (source or binary)**: source
- **MLflow version (run ``mlflow --version``)**: 1.0.0
- **Python version**: 3.6.1
- **npm version (if running the dev UI): 6.7.0
- **Exact command to reproduce**: mlflow run examples/sklearn_elasticnet_wine -P alpha=0.42

### Describe the problem
Install conda from https://repo.anaconda.com/archive/Anaconda2-2019.03-MacOSX-x86_64.sh. Run the script, and allow Conda to manage conda init when asked. This will place the following code in your bash_profile or zshrc:

# >>> conda initialize >>>

__conda_setup="$('/Users/ankit.mathur/anaconda2/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/ankit.mathur/anaconda2/etc/profile.d/conda.sh" ]; then
        . "/Users/ankit.mathur/anaconda2/etc/profile.d/conda.sh"
    else
        export PATH="/Users/ankit.mathur/anaconda2/bin:$PATH"
    fi
fi
unset __conda_setup

It seems that when this happens, it goes through the if block and not the else block, never adding bin to the path. This means that `conda activate` works but `source activate` does not. This means that running the tutorial at: https://mlflow.org/docs/latest/tutorial.html breaks when you do `mlflow run` because that generates a new conda environment and tries to switch to it by doing source activate.

**Comment by ahshanmd** [comment]
@ankitmathur-db - can you try adding into your .bash_profile , this may help in resolving the issue

> export PATH="/Users/mlflow/anaconda3/bin:$PATH"
> 
> # >>> conda initialize >>>
> # !! Contents within this block are managed by 'conda init' !!

**Comment by ankitmathur-db** [comment]
@ahshanmd yes that is a known fix, but MLFlow should be able to detect this and not force users to adjust their bash profile

**Comment by devenxu1985** [comment]
i activate a venv and  run with --no-conda to solve it.

**Comment by ankitmathur-db** [comment]
Yeah that seems to work as well! We're looking into a more principled way of doing this and supporting the way that newer versions of conda recommend activating environments.

**Comment by staghvaeeyan** [comment]
I added added `activate` as an alias for `conda activate` and it works for now until the fix.

**Comment by ankitmathur-db** [comment]
Fixed in 1.1

**Comment by SaadEphlux** [comment]
Hey I am still experiencing the same issue on mlflow v1.4. 

`mlflow run . --experiment-id 2
2020/01/03 15:08:17 INFO mlflow.projects: === Created directory C:\Users\Ayesha\AppData\Local\Temp\tmp57ohwvbq for downloading remote URIs passed to arguments of type 'path' ===
2020/01/03 15:08:17 INFO mlflow.projects: === Running command 'conda activate mlflow-993b0415dc5007c5c65b621a25b4f512e651ad04 && python api.py 5000' in run with ID 'c9c93c393c3c4f5e91341695fb840963' ===

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
If using 'conda activate' from a batch script, change your
invocation to 'CALL conda.bat activate'.

To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - cmd.exe
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.`

Any help would be appreciated.

**Comment by suresh88** [comment]
I am having the trouble accessing the mlflow serve url
System Information:
OS: ubuntu 18.04
mlflow version: 1.6.0
python version: 3.7.3

commands to reproduce:
**mlflow run sklearn_logistic_regression**
**mlflow models serve -m runs:/6456aa2de1f84dce91c190bf93fc2431/model --port 3456**
facing the **Not Found** error all the time

Is there any permanent solution available?

**Comment by fabions** [comment]
> 
> 
> Hey I am still experiencing the same issue on mlflow v1.4.
> 
> `mlflow run . --experiment-id 2
> 2020/01/03 15:08:17 INFO mlflow.projects: === Created directory C:\Users\Ayesha\AppData\Local\Temp\tmp57ohwvbq for downloading remote URIs passed to arguments of type 'path' ===
> 2020/01/03 15:08:17 INFO mlflow.projects: === Running command 'conda activate mlflow-993b0415dc5007c5c65b621a25b4f512e651ad04 && python api.py 5000' in run with ID 'c9c93c393c3c4f5e91341695fb840963' ===
> 
> CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
> If using 'conda activate' from a batch script, change your
> invocation to 'CALL conda.bat activate'.
> 
> To initialize your shell, run
> 
> ```
> $ conda init <SHELL_NAME>
> ```
> 
> Currently supported shells are:
> 
>     * bash
> 
>     * cmd.exe
> 
>     * fish
> 
>     * tcsh
> 
>     * xonsh
> 
>     * zsh
> 
>     * powershell
> 
> 
> See 'conda init --help' for more information and options.
> 
> IMPORTANT: You may need to close and restart your shell after running 'conda init'.`
> 
> Any help would be appreciated.

The same problem here... I am using:
- windows 10 home
- conda 4.8.2
- anaconda powershell prompt (the same with powershell directly)
Any ideas?

Thank you, very much!

mlflow run examples/sklearn_elasticnet_wine -P alpha=0.42
2020/02/11 17:14:25 INFO mlflow.projects: === Created directory C:\Users\fabio\AppData\Local\Temp\tmpjkdf6pm7 for downloading remote URIs passed to arguments of type 'path' ===
2020/02/11 17:14:25 INFO mlflow.projects: === Running command 'conda activate mlflow-3eee9bd7a0713cf80a17bc0a4d659bc9c549efac && python train.py 0.42 0.1' in run with ID 'dc500a004abe43ca876bf5d7697a5eb4' ===

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
If using 'conda activate' from a batch script, change your
invocation to 'CALL conda.bat activate'.

To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - cmd.exe
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.


2020/02/11 17:14:25 ERROR mlflow.cli: === Run (ID 'dc500a004abe43ca876bf5d7697a5eb4') failed ===

**Comment by pdudzic123** [comment]
It appears that the problem is caused by "&&" in generated command. 
The following command is generated:
`conda activate mlflow-3eee9bd7a0713cf80a17bc0a4d659bc9c549efac && python train.py 0.42 0.1`
and Powershell is unable to parse this command correctly.
The dirty workaround for this is to run:
`conda activate mlflow-3eee9bd7a0713cf80a17bc0a4d659bc9c549efac`
manually before running the
`mlflow run . --no-conda`

Note that:
- i used mlflow-3eee9bd7a0713cf80a17bc0a4d659bc9c549efac as conda env. This env was created by mlflow and it changes. You can find your envs by executing ` conda env list`
-I added --no-conda to the second statement.

I hope they will fix this parsing issue in the near future.
Best

**Comment by cpatdowling** [comment]
> It appears that the problem is caused by "&&" in generated command.
> The following command is generated:
> `conda activate mlflow-3eee9bd7a0713cf80a17bc0a4d659bc9c549efac && python train.py 0.42 0.1`
> and Powershell is unable to parse this command correctly.
> The dirty workaround for this is to run:
> `conda activate mlflow-3eee9bd7a0713cf80a17bc0a4d659bc9c549efac`
> manually before running the
> `mlflow run . --no-conda`
> 
> Note that:
> 
> * i used mlflow-3eee9bd7a0713cf80a17bc0a4d659bc9c549efac as conda env. This env was created by mlflow and it changes. You can find your envs by executing ` conda env list`
>   -I added --no-conda to the second statement.
> 
> I hope they will fix this parsing issue in the near future.
> Best

I'm facing an identical issue. Running with just the no conda flag,

`mlflow run . --no-conda`

directly from the conda shell with the base environment seems to work on example runs like mlflow/examples/sklearn_elasticnet_wine. No need to switch conda environments
