### ISSUE TITLE
MLflow UI metrics view displays absolute time with wrong values

### ISSUE THREAD

**Issue by Ahmedn1** [mlflow/mlflow#1798]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: Nope
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **MLflow installed from (source or binary)**:  Binary using pip
- **MLflow version (run ``mlflow --version``)**: mlflow 1.0.0
- **Python version**: 3.6.7
- **Exact command to reproduce**: mlflow.log_metric(run_id, 'name', value)

### Describe the problem
When I log a metric value to MlFlow server then I go to the mlflow UI to the mteric view where it has the plot to view the metric value change over time, I find wrong time values for all metrics for all runs.  

When I pick "Time (Wall)" to view absoulte time values, it displays times in "Jan 19, 1970" with 2 second intervals between each value change for the metric which is of course wrong.  

### Code to reproduce issue
That's how I run the server:  
`mlflow server --backend-store-uri [mysql sqlalchemy connection] --host 0.0.0.0 --gunicorn-opts "--access-logfile -" --port 5150 --default-artifact-root [artifact location]`

Then, I use 
`mlflow.log_metric(run_id, 'name', value)`
to log values

**Comment by ustcscgyer** [comment]
I can take a look at this issue

**Comment by dbczumar** [comment]
@Ahmedn1 This should be fixed in MLflow 1.2; can you try logging metrics using version 1.2 and let me know if this persists?

**Comment by Ahmedn1** [comment]
@dbczumar Nope, I upgraded to 1.2 and it didn't fix the problem.

**Comment by ustcscgyer** [comment]
I have a fresh reinstalled MLflow, and cannot reproduce the error. Here is a screenshot of running 
```
import mlflow
mlflow.log_metrics('x', 0.1)
mlflow.log_metrics('x', 0.2)
mlflow.log_metrics('x', 0.3)
mlflow.log_metrics('x', 0.4)
```
![image](https://user-images.githubusercontent.com/12961341/64079877-32c43b00-cca2-11e9-9fbc-db1a23f18d84.png)

@Ahmedn1 Can you provide the exact code you used to produce the error and show us a screenshot of the wrong timestamp

**Comment by Ahmedn1** [comment]
@ustcscgyer 
```
from mlflow.tracking import MlflowClient
mlflow_client = MlflowClient(MLFLOW_URI)
r = mlflow_client.create_run('2')
mlflow_client.log_metric(r.info.run_id, 'M1', 1)
mlflow_client.log_metric(r.info.run_id, 'M1', 15)
mlflow_client.log_metric(r.info.run_id, 'M1', 100)
```

![Screenshot from 2019-09-02 01-55-09](https://user-images.githubusercontent.com/4731542/64083808-3fd63e00-cd25-11e9-854c-162ddafc8eb6.png)

**Comment by ustcscgyer** [comment]
Error reproduced. Trying to identify the issue.

**Comment by ustcscgyer** [comment]
Found the problem. The `mlflow.log_metrics` uses milliseconds, but `mlflow_client.log_metrics` uses seconds as the timestamp. I will create a PR to fix this.

**Comment by ustcscgyer** [comment]
@Ahmedn1 Issues should be fixed by this PR: #1804

**Comment by Ahmedn1** [comment]
@ustcscgyer Great. I hope this will be pushed into a release soon. 
Thank you

**Comment by ustcscgyer** [comment]
@Ahmedn1 This issue should be resolved.
@dbczumar I cannot close this issue. Can you please tell me how I can gain permission to do so?

**Comment by dbczumar** [comment]
Fixed in #1804, which has been merged
