### ISSUE TITLE
[FR] Reduce Docker Image Size for Predict

### ISSUE THREAD

**Issue by sanketrk** [mlflow/mlflow#2426]
### Motivation
Docker Image produced by MLFlow for predicting the models is supposed to be the most portable format but unfortunately, the docker image produced by MLFlow is of huge size. We tried with a simple model file with 1kb size (a simple regression model) but the resultant docker image is 3.3 GB.  We are trying to deploy these docker images (about 60) in Kubernetes but since K8s nodes will have limited resources, docker images of this size make mlflow a non-viable option. 
### Proposed Changes
Please let us know how the docker image size for predicting the model can be reduced.

**Comment by QuentinAmbard** [comment]
We should avoid packaging the jar files if it's a python served model, and remove condas for java (MLeap) serving. 
It'll also reduce the build time

I suggest we add the libraries (python or java) depending on the serving flavor of the model we download in the the `copy_model_into_container` function instead of hardcoding all the dependancies in `docker_utils.py`

For java models, maven shouldn't be packaged in the image. We should use a first image to run the build, and then copy the resulting jars in the final image.

If it's the best way to improve the image size & the build time I can implement it.

**Comment by vadakattu** [comment]
Hey Quentin,

Just wondering if there was any sense of prioritisation of this feature, as I think it would be a great enhancement?

I've taken a look at `docker_utils.py` and can have a go at an initial patch which strips out the java dependencies from the `_DOCKERFILE_TEMPLATE` & `_get_mlflow_install_step`, given an optional `python_only` arg to `_build_image`, because I think it may be marginally preferable image size/caching wise than installing the dependencies slightly later on as part of the `custom_setup_steps_hook`

**Comment by QuentinAmbard** [comment]
Yes I've started a PR and removing the java part when only python is needed, but also removing the conda env when the serving layer is in java.
Will update the ticket soon with the PR content

**Comment by vadakattu** [comment]
That's awesome, thanks!

As a tangential idea, it would also be great to add a `cached_image` arg to the `_build_image` func

i.e. `["docker", "build", "-t", image_name, "-f", "Dockerfile", ".", "--cache-from", cached_image]`

(Happy to raise a PR if it's outside the scope of the changes you're planning to make)

**Comment by ambiSanthu** [comment]
I have worked on optimising the docker image size. I am able to reduce the size from 3.45GB to 1.41GB. I have done the following changes. I am planning to generalize the changes and raise a PR.
1. As we were using only python model serve, removed all java dependencies like maven downloads and maven builds.
2. Used the base miniconda environment instead of creating a new virtual env "custom_env". 
3. Make --no-conda as True by default. 
4. Also from conda.yaml install only the required dependencies to serve the model (instead of creating a new environment with all the dependencies)

**Comment by ambiSanthu** [comment]
I have created a pull request #2496 and all default test cases succeeded. I have added a new flag "--python-only" and "--no-conda" to build a docker image without java jar files and uses the base conda environment (doesn't create new virtual environment custom_env). 

The model that I have tested created a docker image of size 2.11GB and after optimization docker image size is 886MB.

Please review the code changes.

**Comment by ambiSanthu** [comment]
With my new changes, docker image is created either for python flavor or java flavor based on the model for which docker image is being created for.

With the new argument added to build-docker  ``--no-conda`` that doesn't create a new conda environment "custom_env" instead uses the default miniconda base environment.

The current docker image size for sklearn iris example is 3.21GB and with the new changes docker image size is reduced to 2.14GB and by using --no-conda option (ie., using base miniconda environment), docker image size can be further reduced to 887MB.

**Comment by smurching** [comment]
Apologies for the delay, thanks all for chiming in! @ambiSanthu the approach of adding dependencies based on the model's flavor makes sense. I wonder if instead of adding a `--no-conda` option, it would make sense to simply remove the base miniconda image to save space (not sure how many models can be served solely using the base miniconda image). Thoughts?

**Comment by ambiSanthu** [comment]
As per the docker image creation flow, a new conda env called "custom_env" is being created and dependencies from conda.yml is installed in this custom_env. With --no-conda option, I am not creating the custom_env but parsing the conda.yml and installing the dependencies directly into base env. Hence I make sure required dependencies are installed for the model to run.

**Comment by no-blockers** [comment]
Hi, 

I'm very interested in this issue! We want to deploy tens/hundreds of models using mlflow build-docker, and the image size is clearly a blocker!

In general, I have 2 comments:
1. The docker image already provides a decent form of virtualization. Creating another conda environment inside it can be redundant.  
2. I would imagine an even more customized feature (please point me to an issue if created before), which allows a user to reference his pre-written Docker template file to create the model image. Currently there are some dependencies hard-coded [here](https://github.com/mlflow/mlflow/blob/master/mlflow/models/docker_utils.py#L14). I see the PR #2496  split it into 2 for Java and Python separately, but that still looks a little rigid to me

**Comment by NilakshanKunananthaseelan** [comment]
Any working updates in this issue?

**Comment by dhirajsuvarna** [comment]
any updates on this?

**Comment by B-Step62** [comment]
Hi all! We have merged [the PR](https://github.com/mlflow/mlflow/pull/10954) that applies following optimizations. This will be released in next MLflow version unless we find a major issue.
1. Not install Java and related packages for Python flavors.
2. Use Python-slim base image rather than Ubuntu when applicable.
3. If 2 is applied, not create virtualenv/conda environment inside the container.

As a result, the image size for a small scikit-learn model is now reduced to less than 1GB. But please let us know if you have more ideas to improve further!

**Comment by tugbayatilla** [comment]
I guess, i am the only one still having this issue in 2026!
Eventhough the flavor is python_func, it is using ubuntu instead of python-slim image
