### ISSUE TITLE
mlflow 1.6 - accessing artifacts from tracking uri fails

### ISSUE THREAD

**Issue by mowrang** [mlflow/mlflow#2495]
I have a setup a mlflow server on Azure Kubernete. 

I setup mlflow with the tracking uri pointing to my server. 

I log metrics and tags to the server. Then I log artifacts to Azure blob storage. 

The model successfully gets logged to blonb storage. 

However, when I click on the run to see the artifacts I get the below error: 
Something went wrong
If this error persists, please report an issue on our GitHub page.

**Comment by AdamBarnhard** [comment]
@mowrang do you have a way to see the logs running behind the server? You should be able to see whats triggering this error

**Comment by mowrang** [comment]
Here is the error log:

2020/02/27 18:20:57 ERROR mlflow.server: Exception on /ajax-api/2.0/preview/mlflow/model-versions/search [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/mlflow/server/handlers.py", line 137, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/mlflow/server/handlers.py", line 581, in _search_model_versions
    model_versions_detailed = _get_model_registry_store().search_model_versions(
AttributeError: 'NoneType' object has no attribute 'search_model_versions'
2020/02/27 18:20:58 ERROR mlflow.server: Exception on /ajax-api/2.0/preview/mlflow/artifacts/list [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/mlflow/server/handlers.py", line 137, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/mlflow/server/handlers.py", line 394, in _list_artifacts
    artifact_entities = _get_artifact_repo(run).list_artifacts(path)
  File "/usr/local/lib/python3.7/site-packages/mlflow/store/artifact/azure_blob_artifact_repo.py", line 94, in list_artifacts
    results = self.client.list_blobs(container, prefix=prefix, delimiter='/', marker=marker)
  File "/usr/local/lib/python3.7/site-packages/azure/storage/blob/baseblobservice.py", line 1214, in list_blobs
    resp = self._list_blobs(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/azure/storage/blob/baseblobservice.py", line 1285, in _list_blobs
    return self._perform_request(request, _convert_xml_to_blob_list, operation_context=_context)
  File "/usr/local/lib/python3.7/site-packages/azure/storage/storageclient.py", line 280, in _perform_request
    raise ex
  File "/usr/local/lib/python3.7/site-packages/azure/storage/storageclient.py", line 248, in _perform_request
    raise ex
  File "/usr/local/lib/python3.7/site-packages/azure/storage/storageclient.py", line 235, in _perform_request
    _http_error_handler(HTTPError(response.status, response.message, response.headers, response.body))
  File "/usr/local/lib/python3.7/site-packages/azure/storage/_error.py", line 114, in _http_error_handler
    raise AzureHttpError(message, http_error.status)
azure.common.AzureMissingResourceHttpError: The specified resource does not exist.
<?xml version="1.0" encoding="utf-8"?><Error><Code>ResourceNotFound</Code><Message>The specified resource does not exist.
RequestId:ba5bacd5-901e-007a-4c9a-ed621f000000
Time:2020-02-27T18:20:58.1940890Z</Message></Error>

**Comment by mowrang** [comment]
hi @AdamBarnhard, 
Do have any clue based on the logs on how I should debug this? Any idea is appreciated as I am new to this and a bit lost. 
thanks!

**Comment by mowrang** [comment]
Hi @AdamBarnhard, 

I am using mlflow version 1.6.0. which version of azure-storage have you tested this with? 

thanks, 

Maryam

**Comment by mowrang** [comment]
@AdamBarnhard , 

ok it looks like you have been using azure-storage 0.36.0 for a while - which is my version. 

so I have another question, is there any way to get more verbose logs when running mlflow server?

**Comment by mowrang** [comment]
thanks @AdamBarnhard 
you mean this? 
mlflow server --backend-store-uri /mlruns --default-artifact-root "$MLFLOW_SERVER_DEFAULT_ARTIFACT_ROOT" --host 0.0.0.0 --gunicorn-opts "--log-file -"

**Comment by mowrang** [comment]
@AdamBarnhard I have duplicated your list_artifacts function in mlflow/store/artifact/azure_blob_artifact_repo.py 

when I have 
prefix = dest_path + "/"
I get no blob

but when I have 
prefix = dest_path
I can get the list of blobs

**Comment by cdeptuckUEI** [comment]
Can confirm this happens as well, logging is very sparse with nothing useful, all storage keys, etc have been crossed checked and functioning as intended.

**Comment by cdeptuckUEI** [comment]
Tracking flow server has 2 500 server errors when trying to access details on the experiment
![image](https://user-images.githubusercontent.com/61163180/77572586-7b388580-6e8c-11ea-8c22-2ce5aad52546.png)

**Comment by cdeptuckUEI** [comment]
Fixed on our side, looks like the issue possibly occured due to azure storage environment variable both being present even though one was blank at runtime.
AZURE_STORAGE_ACCESS_KEY
AZURE_STORAGE_CONNECTION_STRING

**Comment by dbczumar** [comment]
Hi folks, please let me know if Azure storage configurations are an ongoing issue with MLflow - it sounds like @cdeptuckUEI 's suggestion was sufficient to resolve the problem. Accordingly, I'm going to go ahead and close this issue. Feel free to reopen it if necessary!

**Comment by tuhinmallick** [comment]
I am still having the problem even though I have setup the environement variables properly

` ERROR mlflow.server: Exception on /ajax-api/2.0/preview/mlflow/artifacts/list [GET]
Traceback (most recent call last):
  File "C:\Util\Anaconda3\envs\Working\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Util\Anaconda3\envs\Working\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request       
    rv = self.handle_user_exception(e)
  File "C:\Util\Anaconda3\envs\Working\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request       
    rv = self.dispatch_request()
  File "C:\Util\Anaconda3\envs\Working\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Util\Anaconda3\envs\Working\lib\site-packages\mlflow\server\handlers.py", line 238, in wrapper
    return func(*args, **kwargs)
  File "C:\Util\Anaconda3\envs\Working\lib\site-packages\mlflow\server\handlers.py", line 298, in wrapper
    return func(*args, **kwargs)
  File "C:\Util\Anaconda3\envs\Working\lib\site-packages\mlflow\server\handlers.py", line 571, in _list_artifacts 
    artifact_entities = _get_artifact_repo(run).list_artifacts(path)
  File "C:\Util\Anaconda3\envs\Working\lib\site-packages\mlflow\store\artifact\s3_artifact_repo.py", line 158, in 
list_artifacts
    for result in results:
  File "C:\Util\Anaconda3\envs\Working\lib\site-packages\botocore\paginate.py", line 255, in __iter__
    response = self._make_request(current_kwargs)
  File "C:\Util\Anaconda3\envs\Working\lib\site-packages\botocore\paginate.py", line 334, in _make_request        
    return self._method(**current_kwargs)
  File "C:\Util\Anaconda3\envs\Working\lib\site-packages\botocore\client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\Util\Anaconda3\envs\Working\lib\site-packages\botocore\client.py", line 719, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (SignatureDoesNotMatch) when calling the ListObjectsV2 operation: The request signature we calculated does not match the signature you provided. Check your key and signing method.`

**Comment by Altair-Bueno** [comment]
@tuhinmallick did you manage to fix this issue? I'm experiencing the same with Bitnami Helm Chart
