### ISSUE TITLE
[FR] Resizable sidebar for long experiment names

### ISSUE THREAD

**Issue by jlangballe-miovision** [mlflow/mlflow#2819]
Thank you for submitting a feature request. **Before proceeding, please review MLflow's [Issue Policy for feature requests](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md#feature-requests) and the [MLflow Contributing Guide](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst)**.

**Please fill in this feature request template to ensure a timely and thorough response.**

## Willingness to contribute
The MLflow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an MLflow Plugin or an enhancement to the MLflow code base)?

- [ ] Yes. I can contribute this feature independently.
- [ ] Yes. I would be willing to contribute this feature with guidance from the MLflow community.
- [x] No. I cannot contribute this feature at this time.

## Proposal Summary

The experiment list sidebar is fixed width and truncates long experiment names, making it difficult to sift through. It would be nice to be able to have a resizable sidebar which I could use to look through my experiments easier

<img width="566" alt="mlflow-experiment-list-ui" src="https://user-images.githubusercontent.com/64787634/81738566-e43d8200-9467-11ea-9c36-4271c4a932bb.png">

## Motivation
- What is the use case for this feature?
Allows for longer experiment names to be practical. Enables prefixing experiment names with things like username, issue numbers, architecture, and other meta-information.
- Why is this use case valuable to support for MLflow users in general?
Allows users to have more freedom in how they choose to name experiments.
- Why is this use case valuable to support for your project(s) or organization?
I would like to prefix my experiment names and currently that would make them too long to appear nicely in the UI.
- Why is it currently difficult to achieve this use case? (please be as specific as possible about why related MLflow features and components are insufficient)
If I have many experiments which are named "\<username\>/\<issue name\>/\<experiment name\>" then they will appear truncated in the UI and I am unable to see the descriptive part of the name. Hovering over many of these would be cumbersome to finding the one I want. Additionally, I cannot easily set or search through experiment tags in the UI, so the name is the only place to store information about an experiment.

<img width="248" alt="Screen Shot 2020-05-12 at 3 48 29 PM" src="https://user-images.githubusercontent.com/64787634/81738659-0d5e1280-9468-11ea-8218-0c05ef9915c5.png">

### What component(s), interfaces, languages, and integrations does this feature affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for
Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interfaces
- [x] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Languages 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations

## Details

(Use this section to include any additional information about the feature. If you have a proposal for how to implement this feature, please include it here. For implementation guidelines, please refer to the [Contributing Guide](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst#contribution-guidelines).)

**Comment by andychow-db** [comment]
These seems like a useful feature for users to have. Would you be interested in helping out here?

**Comment by jlangballe-miovision** [comment]
I might be able to take a look this weekend but my web skills are a bit rusty.

**Comment by harupy** [comment]
Fixed by #2827

**Comment by msminhas93** [comment]
This bug is not resolved. The sidebar is still fixed even in the latest version of MLFlow. For long experiment names, it becomes a nightmare to just glance through the experiments:
Would it be possible to:
1. Allow resizing of the side bar as mentioned in this issue.
2. Allow for wrapping of long names to fixed length and showing those in multiple lines as a selectable option.
I really like the interface, but this is a downside than prevent adoption in certain cases.
Hope someone looks into it.

**Comment by niklasvm** [comment]
Hi. I would also like to see this resolved. Experiment names are truncated in the sidebar as well as in the title after selecting the experiment.

**Comment by rokrokss** [comment]
let's just size up the width of the sidebar
