### ISSUE TITLE
[BUG] AzureBlobArtifactRepository.list_artifacts() wrong

### ISSUE THREAD

**Issue by wuqunfei** [mlflow/mlflow#2991]
### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [x] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **OS Platform and Distribution (Mac/Linux/Docker)**:
- **MLflow version (1.9.0/1.8.0)**:
- **Python version(3.6/3.7/3.8)**:
- **SetUp AzureStorage**:

### Describe the problem
Azure Storage aritficats can't download from UI,  in 1.8.0 and 1.9.0 Version, because all AzureBlobArtifactRepository get list method is wrong. 

    def list_artifacts(self, path=None):

alwary return files >=1, even the path is a file. It can impact is_directory method

    class ArtifactRepository:
        def _is_directory(self, artifact_path):
        listing = self.list_artifacts(artifact_path)
        return len(listing) > 0
In the end, in azure download file, in backend, always create direction instead of file name in ArtifactRepository.py abastract class.

    if self._is_directory(artifact_path) 
        return download_artifact_dir(artifact_path)
    else:
        return download_file(artifact_path)

@Asgeir Berland <asgeir.berland@gmail.com>, in this commit. Maybe something broken this logic https://github.com/mlflow/mlflow/pull/2594

### Code to reproduce issue

 1. install azure-storage-blob==12.3.2 and mlflow==1.9.0
 2. Set up AZURE_STORAGE_ARTIFACT in env
 3. Set up AZURE_STORAGE_ACCESS_KEY in env
 4. `mlflow server \
    --backend-store-uri /yourdisk \
    --default-artifact-root $AZURE_STORAGE_ARTIFACT/ \
    --host 0.0.0.0`
  
 5. Training once and try to download the artifact from one of your experiments http://localhost:5000/#/experiments/1

### Other info / logs
Get Artifact
    http://localhost:5000/get-artifact?path=random-forest-model%2Fmodel.pkl&run_uuid=79379700d86e45cd8aac1a33ebc7c651

Error Display

      File "/usr/local/lib/python3.8/site-packages/mlflow/server/handlers.py", line 182, in get_artifact_handler
        return send_file(filename, as_attachment=True)
      File "/usr/local/lib/python3.8/site-packages/flask/helpers.py", line 629, in send_file
        file = open(filename, "rb")
    IsADirectoryError: [Errno 21] Is a directory: '/var/folders/h6/0s1kkw2n18z9l2m3l_n9gsfm0000gn/T/tmpb2aw2uu1/random-forest-model/model.pkl'

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [x] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for
Model Registry
- [x] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [x] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [x] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients

Integrations
- [x] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations

**Comment by wuqunfei** [comment]
HI @Trollgeir, yes. I debug inside yesterday. After training successfully, the files have saved on Azure blob storage, but when we want to download the file from Mlflow UI, to click the files like model.pkl, we can never download now. the logic likes following, 

1. Click a file or path on UI, the backend will check it is dir or is a file. but the method  self.list_artifacts(artifact_path) is always return >=1 file.
2. then the method def _is_directory always think it is a dir.
3. then download the file on mlserver will create a dir, even it is a file. for example model.pkl file, in the end, it creates a model.pkl directory. 
4. UI can't download the file, never, because there is now download file, it is a directory instead of it. 

`IsADirectoryError: [Errno 21] Is a directory: '/var/folders/h6/0s1kkw2n18z9l2m3l_n9gsfm0000gn/T/tmpb2aw2uu1/random-forest-model/model.pkl'`

Downdload model.pkl file. 

UI-->Request->Backend( getartifaict URI (Azure Blob)-> check **is file or is dir** -> create a temp file or dir -> download the file--> send file )-->Respponse->Browser

**Comment by wuqunfei** [comment]
```
            if isinstance(r, BlobPrefix):   # This is a prefix for items in a subdirectory
                subdir = posixpath.relpath(path=r.name, start=artifact_path)
                if subdir.endswith("/"):
                    subdir = subdir[:-1]
                infos.append(FileInfo(subdir, True, None))
```

I think some logic in Infos.append(p1, True, P3), this True is wrong because it is a file.

**Comment by Trollgeir** [comment]
Thanks for the find @wuqunfei - I believe this bug has existed since the first implementation.

https://github.com/mlflow/mlflow/pull/3014 should address this.

**Comment by wuqunfei** [comment]
thanks, @Trollgeir for the fix, I saw you commit. Waiting for the next release version.

**Comment by arjundc-db** [comment]
Fixed by #3014. Thanks @Trollgeir

**Comment by wuqunfei** [comment]
Thanks everyone, I tested on my production. It works on 1.11 version.

**Comment by christianbaumberger** [comment]
Hi everyone, I still get the same error. Here my setup:
- MLFlow version 1.25.1
- Artefact Store: Azure Blog Storage
- Authentication via DefaultAzureCredential()
I log a model from a jupyter notebook via python api and it gets correctly logged at the azure container:
![grafik](https://user-images.githubusercontent.com/44830049/167628615-65a82aff-0905-4651-b7fa-b5d432419259.png)

When I download the model again via jupyter notebook, it works fine. Whenever I try to view the files in the mlflow UI, I get the following error:
```
2022/05/10 12:05:17 ERROR mlflow.server: Exception on /get-artifact [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/mlflow/server/__init__.py", line 53, in serve_artifacts
    return get_artifact_handler()
  File "/usr/local/lib/python3.7/site-packages/mlflow/server/handlers.py", line 327, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/mlflow/server/handlers.py", line 409, in get_artifact_handler
    return _send_artifact(artifact_repo, artifact_path)
  File "/usr/local/lib/python3.7/site-packages/mlflow/server/handlers.py", line 318, in _send_artifact
    return send_file(filename, mimetype="text/plain", as_attachment=True)
  File "/usr/local/lib/python3.7/site-packages/flask/helpers.py", line 623, in send_file
    cache_timeout=cache_timeout,
  File "/usr/local/lib/python3.7/site-packages/werkzeug/utils.py", line 491, in send_file
    file = open(path, "rb")  # type: ignore
IsADirectoryError: [Errno 21] Is a directory: '/tmp/tmpncip3mhk/10/f16f98383dea46abbdf8d9835419b6f8/artifacts/testmodel/requirements.txt'
```
Could it still be a similar problem as the one above?
Thanks for your help.
Christian
