### ISSUE TITLE
mlflow not found in r-mlflow-1.10.0 conda environment | mlflow rith R 

### ISSUE THREAD

**Issue by KarimSamehSadek** [mlflow/mlflow#3206]
### System information
- OS: Windows
-source: library(mlflow)
- version: 1.1
- **Python version**:3.6
- **Exact command to reproduce**:
library(mlflow)
install_mlflow(python_version = "3.6")
mlflow_log_param("param1", 5)

### Describe the problem
After installing mlflow in rstudio and run any mlflow command such as mlflow_log_param("param1", 5) i recieve the below error. I tried to manually copy mlflow.exe but this resulted in another problem where every mlflow command fails after 10s, see 
https://stackoverflow.com/questions/63174883/using-mlflow-with-r-operation-failed-after-waiting-for-10-seconds

### Other info / logs
Error in rethrow_call(c_processx_exec, command, c(command, args), stdin,  : 
  Command 'C:/Users/usr/Anaconda3/envs/r-mlflow-1.10.0/mlflow' not found @win/processx.c:994 (processx_exec)
Type .Last.error.trace to see where the error occured

**Comment by haddadz** [comment]
Facing the same issue here in R. However, completely functional in python.

**Comment by lorenzwalthert** [comment]
I can't provide code but I had a very similar problem on my Mac. Then, after restarting RStudio, things worked.Did you try that?

**Comment by KarimSamehSadek** [comment]
> I can't provide code but I had a very similar problem on my Mac. Then, after restarting RStudio, things worked.Did you try that?

Thank you for your input, however I am running on windows and tried this several times and to run on different machines but the problem persists

**Comment by franzbischoff** [comment]
To overcome the first error (processx_exec), set this env_var:

`Sys.setenv("MLFLOW_BIN", "C:/Users/[YOURNAME]/Anaconda3/envs/r-mlflow-1.10.0/Scripts/mlflow")`

the default is `C:/Users/[YOURNAME]/Anaconda3/envs/r-mlflow-1.10.0/mlflow`, that is the wrong path.

**Comment by lorenzwalthert** [comment]
If that turns out to be true, mlflow should look in this place by default too? This should work out of the box without having to set the env variable.

**Comment by lorenzwalthert** [comment]
Here is a minimal GH actions run for version 1.11 that fails on Windows but not on Linux (macOS fails on a known other problem): https://github.com/lorenzwalthert/mlflow-test-3206/runs/1254717629?check_suite_focus=true#step:9:354

Indeed, the executable seems [under `Scripts/`](https://github.com/lorenzwalthert/mlflow-test-3206/runs/1254717629?check_suite_focus=true#step:9:317). 

This basically means the latest version of mlflow is not usable out of the box for R windows users. 😩

**Comment by franzbischoff** [comment]
After that, the bug it this, diggint into the code and running from CLI:

`mlflow server --port 5542 --backend-store-uri "D:\Workspaces\RStudio\mlflow\R\mlflow\mlruns" --host 127.0.0.1 --port 5542 --workers 4`
` "waitress replaces gunicorn on Windows, "
NotImplementedError: waitress replaces gunicorn on Windows, cannot specify --gunicorn-opts or --workers`

**Comment by lorenzwalthert** [comment]
I am not sure this is the problem. I think it's as simple as that the binary is not correctly located. This is my understanding from looking at the error trace posted [above](https://github.com/lorenzwalthert/mlflow-test-3206/runs/1254717629?check_suite_focus=true#step:9:354):

```
 Command 'C:/Miniconda/envs/r-mlflow-1.10.0/mlflow' not found @win/processx.c:994 (processx_exec)>
323

324
 Stack trace:
325

 1. mlflow::mlflow_log_param("param1", 5)
 2. zeallot:::`%<-%`(c(client, run_id), resolve_client_and_run_id(client,  ...
 3. base:::tryCatch(multi_assign(substitute(x), value, parent.frame()),  ...
 4. base:::tryCatchList(expr, classes, parentenv, handlers)
 5. base:::tryCatchOne(tryCatchList(expr, names[-nh], parentenv,  ...
 6. base:::doTryCatch(return(expr), name, parentenv, handler)
 7. base:::tryCatchList(expr, names[-nh], parentenv, handlers[-nh])
 8. base:::tryCatchOne(expr, names, parentenv, handlers[[1L]])
 9. base:::doTryCatch(return(expr), name, parentenv, handler)
 10. zeallot:::multi_assign(substitute(x), value, parent.frame())
 11. mlflow:::resolve_client_and_run_id(client, run_id)
 12. mlflow:::mlflow_get_active_run_id_or_start_run()
 13. rlang:::`%||%`(mlflow_get_active_run_id(), mlflow_id(mlflow_start_run()))
 14. mlflow:::mlflow_id(mlflow_start_run())
 15. mlflow:::mlflow_start_run()
 16. mlflow:::mlflow_client()
 17. mlflow:::new_mlflow_client(tracking_uri)
 18. mlflow:::new_mlflow_client.mlflow_file(tracking_uri)
 19. mlflow:::mlflow_server(file_store = path, port = mlflow_connect_port())
 20. base:::do.call("mlflow_cli", c("server", args, list(background = getOption( ...
 21. mlflow:::mlflow_cli("server", "--port", 5919, "--backend-store-uri",  ...
 22. withr:::with_envvar(env, { ...
 23. base:::force(code)
 24. process$new(mlflow_bin, args = unlist(args), echo_cmd = verbose,  ...
 25. .subset2(public_bind_env, "initialize")(...)
 26. processx:::process_initialize(self, private, command, args, stdin,  ...
 27. rethrow_call(c_processx_exec, command, c(command, args), stdin,  ...

 x Command 'C:/Miniconda/envs/r-mlflow-1.10.0/mlflow' not found @win/processx.c:994 (processx_exec)

**Comment by lorenzwalthert** [comment]
How to fix? I think we need a PR to mlflow that includes:

* A test if the binary can be found and run it to test. I hope something like `system2(mlflow:::python_mlflow_bin(), "--version")` would work (maybe we need to unset some env variables set by the parent process). This test should fail with the current version of mlflow.
* Fix `mlflow:::python_mlflow_bin()` to look in `Scripts/` subfolder for the binary and see all tests passing (hopefully).

**Comment by lorenzwalthert** [comment]
This is a major bug IMO and makes it unusable for R users on windows, so I think we must look into this asap. @smurching @javierluraschi 

Context: The localisation of the executable (the reason this issue was opened) is fundamentally the same as #3319, #1009 and the timeout (described below) the same as #3393 and #3077.

It's apparently more complicated than what I outlined in https://github.com/mlflow/mlflow/issues/3206#issuecomment-708580435. First, there are no windows tests for R, so we can't show (and later test) the problematic behavior. In addition, setting the executable right does not solve the problem, because `mlflow_client()` will still time out as reported in #3393 and #3077. I have the suspicion that the problem occurs within `mlflow:::mlflow_client()` with the file path that is something like `"file://D:/a/mlflow-test-3206/mlflow-test-3206/mlruns"` as shown [here](https://github.com/lorenzwalthert/mlflow-test-3206/runs/1257884865?check_suite_focus=true#step:9:28).  

I think to properly solve this, one needs access to a Windows machine which I currently don't have and I also don't have time to look into this.

**Comment by yitao-li** [comment]
In my quest to get the current CI workflow for MLflow R working on Windows (i.e., https://github.com/mlflow/mlflow/pull/3766) I found out XGBoost installation via Conda is only supported on Linux and MacOS. There may be some workaround for this limitation but we'll also need to think about how maintainable such workaround might be.

I think I should skip installing XGBoost and all XGBoost-related tests on Windows for now.

**Comment by lorenzwalthert** [comment]
I agree @yitao-li. Let's first focus on getting mlflow running for R, as very basic functionality is not there (reprex here: https://github.com/mlflow/mlflow/issues/3206#issuecomment-708535937). You can find some more experimentation I did here: https://github.com/lorenzwalthert/mlflow-test-3206/commits/main. In particular, I got 
```
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Failed to connect to 127.0.0.1 port 5816: Connection refused
Calls: <Anonymous> ... request_fetch -> request_fetch.write_memory -> <Anonymous>
Execution halted
```
with `mlflow:::mlflow_validate_server(client)`  with https://github.com/lorenzwalthert/mlflow/pull/5, which should return the correct number of trailing slashes as described in the PR description, but still does not work. I hope you have an interactive windows env available, this is very annoying to debug otherwise -.- Also, I don't know what the latest version of ML flow is that worked on windows for R - if any.

**Comment by lorenzwalthert** [comment]
also, once running, we can see how the problem with the missing conda package is sovled in Python xgboost

**Comment by yitao-li** [comment]
@javierluraschi @lorenzwalthert the Windows-specific issue here is now fixed in https://github.com/mlflow/mlflow/pull/3766

Also, after addressing a bunch of Windows-related issues, we now finally have most of GitHub CI workflow for MLflow R running on Windows. How exciting is that?

**Comment by lorenzwalthert** [comment]
It's incredibly exciting 😎 🎈 🎉 great work @yitao-li.

**Comment by GitHunter0** [comment]
Unfortunately, this problem still persists and I'm unable to use mlflow with R on Windows

**Comment by lorenzwalthert** [comment]
Yes. I repeat. Mlflow for R does not work on windows currently. One way would be to go finish #3766, the other a fresh start.
