### ISSUE TITLE
[BUG] pydantic v2 issue with lightning

### ISSUE THREAD

**Issue by Mai0313** [mlflow/mlflow#9606]
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

- Client: 2.6.0
- Tracking server: None

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04.6 LTS x86_64
- **Python version**: 3.9.15
- **Lightning Version**: 2.0.8
- **Pytorch related Version**: ~=2.0.1+cu118

## Motivation
According to Pydantic has been updated to V2, some of functions are deprecated such as `validator`, `root_validator`, etc.

## Reason
Mlflow is a useful open source platform that we can track our training process, especially this tool is mainly desigened for machine learning. However, lightning has been upgrade to 2.0.8, which required newer pydantic. I think this is a good point to start upgrading it.

### Tracking information

```shell
MLflow version: 2.6.0
System information: Linux #106~18.04.1-Ubuntu SMP Fri Jan 7 07:23:53 UTC 2022
Python version: 3.9.15
MLflow version: 2.6.0
MLflow module location: path/to/myfolder/python3.9/site-packages/mlflow/__init__.py
Tracking URI: file:///path/to/myfolder/mlruns
Registry URI: file:///path/to/myfolder/mlruns
Active experiment ID: 0
Active run ID: 49c6f793ead945afa417c85b8b061455
Active run artifact URI: file:///path/to/myfolder/mlruns/0/49c6f793ead945afa417c85b8b061455/artifacts
MLflow dependencies: 
  Flask: 2.3.3
  Jinja2: 3.1.2
  alembic: 1.12.0
  click: 8.1.7
  cloudpickle: 2.2.1
  databricks-cli: 0.17.7
  docker: 6.1.3
  entrypoints: 0.4
  gitpython: 3.1.35
  gunicorn: 20.1.0
  importlib-metadata: 6.8.0
  markdown: 3.4.4
  matplotlib: 3.7.2
  numpy: 1.25.2
  packaging: 23.1
  pandas: 2.1.0
  protobuf: 4.24.3
  pyarrow: 12.0.1
  pytz: 2023.3.post1
  pyyaml: 6.0.1
  querystring-parser: 1.2.4
  requests: 2.31.0
  scikit-learn: 1.3.0
  scipy: 1.11.2
  sqlalchemy: 1.4.49
  sqlparse: 0.4.4
```

### Code to reproduce issue

simply run with the newest [pytorch lightning](https://pypi.org/project/lightning/); you will see the error

### Stack trace

```
(torch2) ...@...:~/...$ python src/train.py experiment=md14
Traceback (most recent call last):
  File "/path/to/myfolder//src/train.py", line 7, in <module>
    import lightning as L
  File "/path/to/myfolder/.conda/envs/torch2/lib/python3.9/site-packages/lightning/__init__.py", line 25, in <module>
    from lightning.pytorch.callbacks import Callback  # noqa: E402
  File "/path/to/myfolder/.conda/envs/torch2/lib/python3.9/site-packages/lightning/pytorch/__init__.py", line 26, in <module>
    from lightning.pytorch.callbacks import Callback  # noqa: E402
  File "/path/to/myfolder/.conda/envs/torch2/lib/python3.9/site-packages/lightning/pytorch/callbacks/__init__.py", line 29, in <module>
    from lightning.pytorch.callbacks.pruning import ModelPruning
  File "/path/to/myfolder/.conda/envs/torch2/lib/python3.9/site-packages/lightning/pytorch/callbacks/pruning.py", line 28, in <module>
    from lightning.pytorch.core.module import LightningModule
  File "/path/to/myfolder/.conda/envs/torch2/lib/python3.9/site-packages/lightning/pytorch/core/__init__.py", line 16, in <module>
    from lightning.pytorch.core.module import LightningModule
  File "/path/to/myfolder/.conda/envs/torch2/lib/python3.9/site-packages/lightning/pytorch/core/module.py", line 62, in <module>
    from lightning.pytorch.loggers import Logger
  File "/path/to/myfolder/.conda/envs/torch2/lib/python3.9/site-packages/lightning/pytorch/loggers/__init__.py", line 19, in <module>
    from lightning.pytorch.loggers.mlflow import _MLFLOW_AVAILABLE, MLFlowLogger  # noqa: F401
  File "/path/to/myfolder/.conda/envs/torch2/lib/python3.9/site-packages/lightning/pytorch/loggers/mlflow.py", line 42, in <module>
    import mlflow
  File "/path/to/myfolder/.conda/envs/torch2/lib/python3.9/site-packages/mlflow/__init__.py", line 247, in <module>
    from mlflow import gateway  # noqa: F401
  File "/path/to/myfolder/.conda/envs/torch2/lib/python3.9/site-packages/mlflow/gateway/__init__.py", line 1, in <module>
    from mlflow.gateway.fluent import get_route, search_routes, query, create_route, delete_route
  File "/path/to/myfolder/.conda/envs/torch2/lib/python3.9/site-packages/mlflow/gateway/fluent.py", line 4, in <module>
    from mlflow.gateway.client import MlflowGatewayClient
  File "/path/to/myfolder/.conda/envs/torch2/lib/python3.9/site-packages/mlflow/gateway/client.py", line 8, in <module>
    from mlflow.gateway.config import Route
  File "/path/to/myfolder/.conda/envs/torch2/lib/python3.9/site-packages/mlflow/gateway/config.py", line 66, in <module>
    class OpenAIConfig(ConfigModel):
  File "/path/to/myfolder/.conda/envs/torch2/lib/python3.9/site-packages/mlflow/gateway/config.py", line 79, in OpenAIConfig
    @root_validator(pre=False)
  File "/path/to/myfolder/.conda/envs/torch2/lib/python3.9/site-packages/pydantic/deprecated/class_validators.py", line 228, in root_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

For further information visit https://errors.pydantic.dev/2.1.1/u/root-validator-pre-skip
```

### Other info / logs

If this issue is not solved, we wont be able to train with lightning>2.0.0

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/gateway`: AI Gateway service, Gateway client APIs, third-party Gateway integrations
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [X] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
@Mai0313 Should be fixed by https://github.com/mlflow/mlflow/pull/9337

**Comment by harupy** [comment]
We're going to release 2.7.0 soon :)

**Comment by Mai0313** [comment]
> 

I just saw this, but I still see that there is lots of usage on some deprecated function such as `validator` should be replaced to `field_validator` and `root_validator` should be replaced to `model_validator`

In the meantime, I have fix all on my own branch which is forked from master

**Comment by Mai0313** [comment]
In the meantime, there is a conflict with pydantic which is `model_server_url` naming issue

it will pop out `UserWarning: Field "model_server_url" has conflict with protected namespace "model_".` during training and using mlflow.
I am happy to help, so it ups to you tho.

**Comment by Mai0313** [comment]
@harupy 
I just saw this, but I still see that there is lots of usage on some deprecated function such as `validator` should be replaced to `field_validator` and `root_validator` should be replaced to `model_validator`

In the meantime, I have fixed all issues I have mentioned on my own branch which is forked from master; and I am glad to have a chance to help you.
I am currently working at Mediatek, so I dont need a job, I only wanna help and also fix my project

**Comment by harupy** [comment]
> I still see that there is lots of usage on some deprecated function

Yes, we made that decision to support both v1 and v2. Any better way to support both versions?

**Comment by harupy** [comment]
@Mai0313 

> However, lightning has been upgrade to 2.0.8, which required newer pydantic

Does lighting require pydantic v2?

**Comment by Mai0313** [comment]
and also this 
```
UserWarning: Field "model_server_url" has conflict with protected namespace "model_".
E           
E           You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
E             warnings.warn(
E           /path/to/folder/torch2/lib/python3.9/site-packages/pydantic/_internal/_config.py:269: UserWarning: Valid config keys have changed in V2:
E           * 'schema_extra' has been renamed to 'json_schema_extra'
E             warnings.warn(message, UserWarning)
E           In 'train.yaml': Could not find 'model/mnist'
```
